@api = http://localhost:5000/api/pedidos

### GET ALL
GET {{api}}/

### CREATE
POST {{api}}/
Content-Type: application/json

{
  "mesa":2,
  "productos": [
    {
      "id": 1,
      "id": 1,
      "nombre": "Ron 5 años",
      "valor": "90000",
      "imagen": "https:&#x2F;&#x2F;i0.wp.com&#x2F;www.licoresmedellin.com&#x2F;wp-content&#x2F;uploads&#x2F;2022&#x2F;06&#x2F;Mezcal-Union-Kit-VIEJO-700ml.jpg?fit=600%2C800&amp;ssl=1",
      "unidades": 2
    },
    {
      "id": 2,
      "nombre": "Ron 15 Años",
      "valor":110000,
      "imagen":"https://i0.wp.com/www.licoresmedellin.com/wp-content/uploads/2022/06/Mezcal-Union-Kit-VIEJO-700ml.jpg?fit=600%2C800&ssl=1",
      "unidades":2
    }
  ],
  "total": 290000,
  "usuario_id":1,
  "sede_id":1
}

### GET BY ID
GET {{api}}/5

### UPDATE BY ID
PATCH {{api}}/1
Content-Type: application/json

{
    "email":"admin@correo.com",
    "password": "Qaws12pj-22"
}

### DELETE BY ID
DELETE {{api}}/5


###
POST {{api}}/login
Content-Type: application/json

{
    "email":"admin@correo.com",
    "password": "Qaws12pj-22"
}

###
GET {{api}}/get/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU3OTA0ODQzLCJleHAiOjE2NTc5OTEyNDN9.BWER5HTze2tyrtet8tW_fb9ZNtkgEK8FmBjrjR-ETq0

